version: "2.4"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - server

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - server

  server:
    build:
      context: ./server/
      target: dev
    ports:
      - 4000:4000
    volumes:
      - ./server/:/node/app
      - /node/app/node_modules
    depends_on:
      - redis
      - mongo
    networks:
      - server

volumes:
  redis-data: {}
  mongo-data: {}

networks:
  server: {}
